config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # each client will have a different homepage
  root 'client/sites#show'

  namespace :admin do
    resources :appointments
    resources :patient_sessions
    resources :users

    resources :sessions, only: %i[create destroy]
  end

  namespace :client do
    resources :sites, only: %i[show]
    resources :users, only: %i[new show]

    resources :sessions, only: %i[create destroy]
  end

  get 'admin_logout', to: 'admin/sessions#destroy', as: 'admin_logout'
  get 'admin_dashboard', to: 'admin/admin#dashboard', as: 'admin_dashboard'
  post 'admin_login', to: 'admin/sessions#create', as: 'admin_login'

  get 'user_signup', to: 'client/users#new', as: 'user_signup'
end

app/models/user.rb
class User < ApplicationRecord
  include Pagination

  has_secure_password

  belongs_to :site
  has_many :appointments
  has_many :patient_sessions, through: :appointments

  default_scope { order(created_at: :desc) }

  validates_presence_of :username, :firstname, :lastname

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :user, only: %i[show edit update destroy]
  before_action :users, only: %i[index]
  before_action :setup_user, only: %i[create]

  def index
    respond_to do |format|
      format.html { @users }
      format.json { render json: @users }
    end
  end

  def create
    respond_to do |format|
      if @user.save
        format.json { render json: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json { render json: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  private

  def user
    @user ||= current_site.users.where(id: params[:id]).first
  end

  def users
    @users ||= current_site.users.page(params[:page])
  end

  def setup_user
    @user          = current_site.users.build(user_params)
    @user.password = PasswordStrategy.random if user_params[:password].blank?
  end

  def user_params
    params.fetch(:user).permit(
      :username,
      :firstname,
      :lastname,
      :password,
      :contact_number,
      :email_address
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.haml
%h1 Users

%table.table
  %thead.thead-dark
    %tr
      %th(scope='col') ID
      %th(scope='col') Username
      %th(scope='col') First Name
      %th(scope='col') Last Name
      %th(scope='col')
  %tbody
    - @users.each do |user|
      %tr
        %th(scope='row')= "#{user.id}"
        %td= link_to "#{user.username}", user, :target => '_blank'
        %td= user.firstname
        %td= user.lastname
        %td
          = link_to user, method: :delete, data: { confirm: 'Are you sure?' } do
            %i.fa.fa-trash.fa-lg
            Delete?

%br
= link_to new_user_path do
  %i.fa.fa-plus.fa-lg
  Add a new User

app/views/users/new.haml
%h1 New User

= render 'form', user: @user

= link_to 'Back', users_path