config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # each client will have a different homepage
  root 'client/sites#show'

  namespace :admin do
    resources :appointments
    resources :patient_sessions
    resources :users

    resources :sessions, only: %i[create destroy]
  end

  namespace :client do
    resources :sites, only: %i[show]
    resources :users, only: %i[new show]

    resources :sessions, only: %i[create destroy]
  end

  get 'admin_logout', to: 'admin/sessions#destroy', as: 'admin_logout'
  get 'admin_dashboard', to: 'admin/admin#dashboard', as: 'admin_dashboard'
  post 'admin_login', to: 'admin/sessions#create', as: 'admin_login'

  get 'user_signup', to: 'client/users#new', as: 'user_signup'
end

app/models/user.rb
class User < ApplicationRecord
  include Pagination

  has_secure_password

  belongs_to :site
  has_many :appointments
  has_many :patient_sessions, through: :appointments

  default_scope { order(created_at: :desc) }

  validates_presence_of :username, :firstname, :lastname

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :user, only: %i[show edit update destroy]
  before_action :users, only: %i[index]
  before_action :setup_user, only: %i[create]

  def index
    respond_to do |format|
      format.html { @users }
      format.json { render json: @users }
    end
  end

  def create
    respond_to do |format|
      if @user.save
        format.json { render json: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json { render json: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html {}
      format.json { head :no_content }
    end
  end

  private

  def user
    @user ||= current_site.users.where(id: params[:id]).first
  end

  def users
    @users ||= current_site.users.page(params[:page])
  end

  def setup_user
    @user          = current_site.users.build(user_params)
    @user.password = PasswordStrategy.random if user_params[:password].blank?
  end

  def user_params
    params.fetch(:user).permit(
      :username,
      :firstname,
      :lastname,
      :password,
      :contact_number,
      :email_address
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.haml
= form_for user, url: { action: 'update' }  do |form|
  .form-group.row
    = form.label :id, class: 'col-sm-2 col-form-label'
    .col-sm-3
      = form.text_field :id, class: 'form-control'
  .form-group.row
    = form.label :username, class: 'col-sm-2 col-form-label'
    .col-sm-3
      = form.text_field :username, class: 'form-control'
  .form-group.row
    = form.label :firstname, class: 'col-sm-2 col-form-label'
    .col-sm-3
      = form.text_field :firstname, class: 'form-control'
  .form-group.row
    = form.label :lastname, class: 'col-sm-2 col-form-label'
    .col-sm-3
      = form.text_field :lastname, class: 'form-control'
  .form-group.row
    = form.label :contact_number, class: 'col-sm-2 col-form-label'
    .col-sm-3
      = form.text_field :contact_number, class: 'form-control'
  .form-group.row
    = form.label :email_address, class: 'col-sm-2 col-form-label'
    .col-sm-3
      = form.text_field :email_address, class: 'form-control'

app/views/admin/users/_user.haml
%tbody
  %tr(scope="row")
    %td= user.id
    %td= link_to user.username, edit_admin_user_path(user), target: '_blank'
    %td= user.firstname
    %td= user.lastname
    %td= user.contact_number
    %td= user.email_address
    %td.icon-columns= fa_icon 'trash lg'

app/views/admin/users/edit.haml
= render 'form', user: @user
%hr
%button Book an Appointment

app/views/admin/users/index.haml
%h5.ml-2 Patient List

%table.table.table-bordered.table-hover
	%thead.bg-light
		%th(scope="col") ID
		%th(scope="col") Username
		%th(scope="col") First Name
		%th(scope="col") Last Name
		%th(scope="col") Contact Number
		%th(scope="col") Email Address
		%th(scope="col")
	= render partial: 'user', collection: @users

= paginate @users

app/views/admin/users/new.haml
%h1 New User

= render 'form', user: @user

app/views/admin/users/show.haml
= @user.username
= @user.firstname
= @user.lastname

= link_to edit_admin_user_path(@user) do
  %i.fa.fa-edit.fa-lg
= link_to admin_users_path do
  %i.fa.fa-arrow-circle-left.fa-lg
  All Users

- if current_user
  = link_to 'Logout', logout_path